export const AUTH_CHANGE = 'AUTH_CHANGE';
export const AUTH_POPUP_VISIBLE = 'AUTH_POPUP_VISIBLE';
export const SET_NOTIFICATION_TOKEN = 'SET_NOTIFICATION_TOKEN';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
